services:
  postgresql:
    image: registry.ocp4.example.com:8443/rhel9/postgresql-13:1
    container_name: beeper-db
    networks:
      - beeper-backend
    volumes:
      - beeper-data:/var/lib/pgsql/data
    environment:
      POSTGRESQL_USER: beeper
      POSTGRESQL_PASSWORD: beeper123
      POSTGRESQL_DATABASE: beeper
  api:
    build:
      context: beeper-backend
      dockerfile: Dockerfile
    image: "localhost/beeper-api:v1"
    container_name: beeper-api
    environment:
      DB_HOST: beeper-db
    networks:
      - beeper-backend
      - beeper-frontend
  ui:
    build:
      context: beeper-ui
      dockerfile: Dockerfile
    image: "localhost/beeper-ui:v1"
    container_name: beeper-ui
    ports: 
      - "8080:8080"
    networks:
      - beeper-frontend
volumes:
  beeper-data: 
    external: true
networks:
  beeper-backend: 
    external: true
  beeper-frontend: 
    external: true
